export const studentProfileData = [
  {
    _id: '67c5b09a1e540d0e30858196',
    userId: '67c5b09a1e540d0e30858194',
    studentStatus: 'Old Student',
    isVerified: true,
    createdAt: '2025-03-03T13:37:30.401Z',
    updatedAt: '2025-03-09T15:27:09.683Z',
    age: '25',
    barangay: 'Sipaloc',
    birthPlaceCity: 'Sibutad',
    birthPlaceProvince: 'Zamboanga del Norte',
    birthPlaceRegion: 'Region 9',
    birthday: '2000-11-05T16:00:00.000Z',
    cityMunicipality: 'Sibutad',
    civilStatus: 'single',
    contact: '09530496890',
    district: '1',
    educationAttainment: 'college level',
    employmentStatus: 'employed',
    firstname: 'lalaine',
    lastname: 'dumam-ag',
    learnerOrTraineeOrStudentClassification: 'Others',
    middlename: 'taday',
    nationality: 'Filipino',
    numberStreet: 'Purok 1-B',
    province: 'Zamboanga del Norte',
    region: 'Region 9',
    sex: 'female',
    FathersContact: '09530496890',
    FathersEmail: 'ltdumam28@gmail.com',
    FathersFirstName: 'Marcelino',
    FathersLastName: 'Dumam-ag',
    FathersMiddleName: 'Gumandoy',
    MothersContact: '09530496890',
    MothersEmail: 'ltdumam28@gmail.com',
    MothersFirstName: 'Mariquita',
    MothersLastName: 'Dumam-ag',
    MothersMiddleName: 'Taday',
    cocUrl: null,
    courseId: '67b8038015bb91b25b73684e',
    enrollStatus: 'Pending',
    goodMoralUrl: 'BSCS Logo.png',
    photoUrl: 'BSCS Logo.png',
    primarySchoolName: 'Sipaloc Elementary School',
    primarySchoolYear: '2003',
    psaUrl: 'BSCS Logo.png',
    reportCardUrl: 'BSCS Logo.png',
    secondarySchoolName: 'Colegio SAn Francisco Javier',
    secondarySchoolYear: '2007',
    seniorHighSchoolName: 'n/a',
    seniorHighSchoolStrand: 'n/a',
    seniorHighSchoolYear: 'n/a',
    studentSemester: '2nd semester',
    studentYear: '4th year',
    studentType: 'regular',
  },
  {
    _id: '67c5b0bd1e540d0e3085819d',
    userId: '67c5b0bd1e540d0e3085819b',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-03T13:38:05.250Z',
    updatedAt: '2025-03-24T12:52:19.977Z',
    age: '25',
    barangay: 'Barra',
    birthPlaceCity: 'Dipolog CIty',
    birthPlaceProvince: 'Zamboanga del Norte',
    birthPlaceRegion: 'Region 9',
    birthday: '2000-03-09T16:00:00.000Z',
    cityMunicipality: 'Dipolog City',
    civilStatus: 'single',
    contact: '09123456789',
    district: '1',
    educationAttainment: 'college level',
    employmentStatus: 'unemployed',
    firstname: 'reymond',
    lastname: 'godoy',
    learnerOrTraineeOrStudentClassification: 'Others',
    middlename: 'ramayla',
    nationality: 'Filipino',
    numberStreet: '1',
    province: 'Zamboanga del Norte',
    region: 'Region 9',
    sex: 'male',
    FathersContact: '09123456789',
    FathersEmail: 'marsvelasco@gmail.com',
    FathersFirstName: 'Mon',
    FathersLastName: 'Godoy',
    FathersMiddleName: 'Cruz',
    MothersContact: '09123456789',
    MothersEmail: 'marsvelasco@gmail.com',
    MothersFirstName: 'Reya',
    MothersLastName: 'Godoy',
    MothersMiddleName: 'Ramayla',
    cocUrl: null,
    courseId: '67b8038015bb91b25b73684e',
    enrollStatus: 'Pending',
    goodMoralUrl: 'BSCS Logo.png',
    photoUrl: 'BSCS Logo.png',
    primarySchoolName: 'Barra Central School',
    primarySchoolYear: '2006',
    psaUrl: 'BSCS Logo.png',
    reportCardUrl: 'BSCS Logo.png',
    secondarySchoolName: 'ZNNHS Turno',
    secondarySchoolYear: '2012',
    seniorHighSchoolName: 'n/a',
    seniorHighSchoolStrand: 'ICT',
    seniorHighSchoolYear: '2012',
    studentSemester: '2nd semester',
    studentYear: '4th year',
    studentType: 'regular',
  },
  {
    _id: '67c5b0f11e540d0e308581a4',
    userId: '67c5b0f11e540d0e308581a2',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-03T13:38:57.591Z',
    updatedAt: '2025-03-24T12:38:43.254Z',
    age: '25',
    barangay: 'Minaog',
    birthPlaceCity: 'Dipolog City',
    birthPlaceProvince: 'Zamboanga del Norte',
    birthPlaceRegion: 'Region 9',
    birthday: '2000-03-09T17:00:00.000Z',
    cityMunicipality: 'Dipolog City',
    civilStatus: 'single',
    contact: '09123456789',
    district: '1',
    educationAttainment: 'college level',
    employmentStatus: 'unemployed',
    extensionName: '',
    firstname: 'sopia',
    lastname: 'harun',
    learnerOrTraineeOrStudentClassification: 'Others',
    middlename: 'b',
    nationality: 'Filipino',
    numberStreet: '1',
    province: 'Zamboanga del Norte',
    region: 'Region 9',
    sex: 'female',
    FathersContact: '09123456789',
    FathersEmail: 'harun25@gmail.com',
    FathersFirstName: 'Harun',
    FathersLastName: 'Harun',
    FathersMiddleName: 'Harun',
    MothersContact: '09123456789',
    MothersEmail: 'harun25@gmail.com',
    MothersFirstName: 'Harun',
    MothersLastName: 'Harun',
    MothersMiddleName: 'Harun',
    cocUrl: null,
    courseId: '67b8038015bb91b25b73684e',
    enrollStatus: 'Pending',
    goodMoralUrl: 'pngegg (45).png',
    photoUrl: 'pngegg (45).png',
    primarySchoolName: 'Sawang Elementary School',
    primarySchoolYear: '2000',
    psaUrl: 'pngegg (45).png',
    reportCardUrl: 'pngegg (45).png',
    secondarySchoolName: 'Sawang NHS',
    secondarySchoolYear: '2005',
    seniorHighSchoolName: 'n/a',
    seniorHighSchoolStrand: 'n/a',
    seniorHighSchoolYear: 'n/a',
    studentSemester: '2nd semester',
    studentYear: '3rd year',
    studentType: 'regular',
    scholarshipId: '67e012a751263490c01073b3',
  },
  {
    _id: '67c5b1061e540d0e308581ab',
    userId: '67c5b1061e540d0e308581a9',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-03T13:39:18.539Z',
    updatedAt: '2025-03-24T13:14:57.274Z',
    age: '25',
    barangay: 'Biasong',
    birthPlaceCity: 'Dipolog City',
    birthPlaceProvince: 'Zamboanga del Norte',
    birthPlaceRegion: 'Region 9',
    birthday: '2000-03-23T16:00:00.000Z',
    cityMunicipality: 'Dipolog City',
    civilStatus: 'single',
    contact: '09123456789',
    district: '1',
    educationAttainment: 'college level',
    employmentStatus: 'unemployed',
    firstname: 'jeralyn',
    lastname: 'sumambod',
    learnerOrTraineeOrStudentClassification: 'Others',
    nationality: 'Filipino',
    numberStreet: '1',
    province: 'Zamboanga del Norte',
    region: 'Region 9',
    sex: 'female',
    scholarshipId: '67e159a463e8febce321f1f5',
    FathersContact: '09817120074',
    FathersEmail: 'jerrysumambod@gmail.com',
    FathersFirstName: 'Jerry ',
    FathersLastName: 'Sumambod ',
    FathersMiddleName: 'Randes',
    MothersContact: '09090992402',
    MothersEmail: 'mariasumambodtanaga@gmail.com',
    MothersFirstName: 'Maria',
    MothersLastName: 'Sumambod ',
    MothersMiddleName: 'Mandol',
    cocUrl: null,
    courseId: '67b8038015bb91b25b73684e',
    enrollStatus: 'Pending',
    goodMoralUrl: 'blob',
    photoUrl: 'inbound6180326215241352723.jpg',
    primarySchoolName: 'Biasong Elementary school',
    primarySchoolYear: '2005-2006',
    psaUrl: 'blob',
    reportCardUrl: 'blob',
    secondarySchoolName: 'Biasong Elementary School ',
    secondarySchoolYear: '2014-2015',
    seniorHighSchoolName: 'n/a',
    seniorHighSchoolStrand: 'Barbering ',
    seniorHighSchoolYear: '2019-2020',
    studentSemester: '2nd semester',
    studentYear: '3rd year',
    studentType: 'regular',
  },
  {
    _id: '67ce93f59b82a9319407ab02',
    userId: '67ce93f59b82a9319407ab00',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-10T07:25:41.788Z',
    updatedAt: '2025-03-23T13:54:15.634Z',
    age: '25',
    barangay: 'Olingan',
    birthPlaceCity: 'Dipolog City',
    birthPlaceProvince: 'Zamboanga del Norte',
    birthPlaceRegion: 'Region 9',
    birthday: '2000-03-10T17:00:00.000Z',
    cityMunicipality: 'Dipolog City',
    civilStatus: 'single',
    contact: '09123456789',
    district: '1',
    educationAttainment: 'college level',
    employmentStatus: 'unemployed',
    firstname: 'cristy',
    lastname: 'julian',
    learnerOrTraineeOrStudentClassification: 'Others',
    middlename: 'gebone',
    nationality: 'Filipino',
    numberStreet: '1',
    province: 'Zamboanga del Norte',
    region: 'Region 9',
    sex: 'female',
    FathersContact: '09123456789',
    FathersEmail: 'julian25@gmail.com',
    FathersFirstName: 'Julian',
    FathersLastName: 'Julian',
    FathersMiddleName: 'Julian',
    MothersContact: '09123456789',
    MothersEmail: 'julian25@gmail.com',
    MothersFirstName: 'Julian',
    MothersLastName: 'Julian',
    MothersMiddleName: 'Julian',
    cocUrl: null,
    courseId: '67b8038015bb91b25b73684e',
    enrollStatus: 'Pending',
    goodMoralUrl: 'pngegg (45).png',
    photoUrl: 'pngegg (45).png',
    primarySchoolName: 'Olingan Elementary School',
    primarySchoolYear: '2006',
    psaUrl: 'pngegg (45).png',
    reportCardUrl: 'pngegg (45).png',
    secondarySchoolName: 'ZNNHS',
    secondarySchoolYear: '2010',
    seniorHighSchoolName: 'n/a',
    seniorHighSchoolStrand: 'HUMSS',
    seniorHighSchoolYear: '2015',
    studentSemester: '2nd semester',
    studentYear: '4th year',
    studentType: 'regular',
    scholarshipId: '67e0128751263490c01073a9',
  },
  {
    _id: '67e15f37c092b88ef39caa64',
    userId: '67e15f37c092b88ef39caa62',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-24T13:33:43.619Z',
    updatedAt: '2025-03-24T14:27:52.940Z',
    age: '1825',
    barangay: 'Poblacion',
    birthPlaceCity: 'Dapitan City',
    birthPlaceProvince: 'Zamboanga del Norte',
    birthPlaceRegion: 'Region 9',
    birthday: '0200-03-23T15:54:17.000Z',
    cityMunicipality: 'Dapitan City',
    civilStatus: 'single',
    contact: '09123456789',
    district: '1',
    educationAttainment: 'college level',
    employmentStatus: 'unemployed',
    firstname: 'jubenil',
    lastname: 'saldon',
    learnerOrTraineeOrStudentClassification: 'Others',
    nationality: 'Filipino',
    numberStreet: '1',
    province: 'Zamboanga del Norte',
    region: 'Region 9',
    sex: 'male',
    FathersContact: '09123456789',
    FathersEmail: 'saldon@gmail.com',
    FathersFirstName: 'Saldon',
    FathersLastName: 'Saldon',
    FathersMiddleName: 'Saldon',
    MothersContact: '09123456789',
    MothersEmail: 'saldon@gmail.com',
    MothersFirstName: 'Mary',
    MothersLastName: 'Saldon',
    MothersMiddleName: 'Cruz',
    cocUrl: null,
    courseId: '67b8038015bb91b25b73684e',
    enrollStatus: 'Pending',
    goodMoralUrl: 'BSCS Logo.png',
    photoUrl: 'BSCS Logo.png',
    primarySchoolName: 'Dapitan Central School',
    primarySchoolYear: '2006',
    psaUrl: 'BSCS Logo.png',
    reportCardUrl: 'BSCS Logo.png',
    secondarySchoolName: 'Dapitan City NHS',
    secondarySchoolYear: '2012',
    seniorHighSchoolName: 'n/a',
    seniorHighSchoolStrand: '',
    seniorHighSchoolYear: '',
    studentSemester: '2nd semester',
    studentYear: '3rd year',
    scholarshipId: '67e167658dbc00e962538db0',
    studentType: 'regular',
  },
  {
    _id: '67e15f7982ab96357b120365',
    userId: '67e15f7982ab96357b120363',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-24T13:34:49.681Z',
    updatedAt: '2025-03-30T04:50:27.220Z',
    age: '25',
    barangay: 'Turno',
    birthPlaceCity: 'Dipolog City',
    birthPlaceProvince: 'Zamboanga del Norte',
    birthPlaceRegion: 'Region 9',
    birthday: '2000-03-23T16:00:00.000Z',
    cityMunicipality: 'Dipolog City',
    civilStatus: 'single',
    contact: '09123456789',
    district: '1',
    educationAttainment: 'college level',
    employmentStatus: 'unemployed',
    firstname: 'nikka marie',
    lastname: 'alasa-as',
    learnerOrTraineeOrStudentClassification: 'Solo Parent',
    middlename: 'galan',
    nationality: 'Filipino',
    numberStreet: '2',
    province: 'Zamboanga del Norte',
    region: 'Region 9',
    sex: 'female',
    FathersContact: '09123456789',
    FathersEmail: 'alasa-as@gmail.com',
    FathersFirstName: 'Alasa-as',
    FathersLastName: 'Alasa-as',
    FathersMiddleName: 'Alasa-as',
    MothersContact: '09123456789',
    MothersEmail: 'alasa-as@gmail.com',
    MothersFirstName: 'Mary',
    MothersLastName: 'Alasa-as',
    MothersMiddleName: 'Alasa-as',
    cocUrl: null,
    courseId: '67b8038015bb91b25b73684e',
    enrollStatus: 'Pending',
    goodMoralUrl: 'BSCS Logo.png',
    photoUrl: 'BSCS Logo.png',
    primarySchoolName: 'Dipolog City Central School',
    primarySchoolYear: '2007',
    psaUrl: 'BSCS Logo.png',
    reportCardUrl: 'BSCS Logo.png',
    secondarySchoolName: 'ZNNHS Turno',
    secondarySchoolYear: '2011',
    seniorHighSchoolName: 'n/a',
    seniorHighSchoolStrand: 'ICT',
    seniorHighSchoolYear: '2014',
    studentSemester: '2nd semester',
    studentYear: '2nd year',
    scholarshipId: '67e1670a8dbc00e962538d92',
    studentType: 'regular',
  },
  {
    _id: '67e15f8f82ab96357b12036c',
    userId: '67e15f8f82ab96357b12036a',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-24T13:35:11.665Z',
    updatedAt: '2025-03-30T04:52:45.231Z',
    age: '25',
    barangay: 'Turno',
    birthPlaceCity: 'Dipolog City',
    birthPlaceProvince: 'Zamboanga del Norte',
    birthPlaceRegion: 'Region 9',
    birthday: '2000-03-23T16:00:00.000Z',
    cityMunicipality: 'Dipolog City',
    civilStatus: 'single',
    contact: '09123456789',
    district: '1',
    educationAttainment: 'college level',
    employmentStatus: 'unemployed',
    firstname: 'nikka mae',
    lastname: 'alasa-as',
    learnerOrTraineeOrStudentClassification: 'Solo Parent',
    middlename: 'galan',
    nationality: 'Filipino',
    numberStreet: '2',
    province: 'Zamboanga del Norte',
    region: 'Region 9',
    sex: 'female',
    FathersContact: '09123456789',
    FathersEmail: 'alasa-as@gmail.com',
    FathersFirstName: 'Alasa-as',
    FathersLastName: 'Alasa-as',
    FathersMiddleName: 'Alasa-as',
    MothersContact: '09123456789',
    MothersEmail: 'alasa-as@gmail.com',
    MothersFirstName: 'Mary',
    MothersLastName: 'Alasa-as',
    MothersMiddleName: 'Alasa-as',
    cocUrl: null,
    courseId: '67b8038015bb91b25b73684e',
    enrollStatus: 'Pending',
    goodMoralUrl: 'BSCS Logo.png',
    photoUrl: 'BSCS Logo.png',
    primarySchoolName: 'Dipolog City Central School',
    primarySchoolYear: '2007',
    psaUrl: 'BSCS Logo.png',
    reportCardUrl: 'BSCS Logo.png',
    secondarySchoolName: 'ZNNHS Turno',
    secondarySchoolYear: '2011',
    seniorHighSchoolName: 'n/a',
    seniorHighSchoolStrand: 'ICT',
    seniorHighSchoolYear: '2014',
    studentSemester: '2nd semester',
    studentYear: '2nd year',
    scholarshipId: '67e1671e8dbc00e962538d9c',
    studentType: 'regular',
  },
  {
    _id: '67e15fb182ab96357b120373',
    userId: '67e15fb182ab96357b120371',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-24T13:35:45.665Z',
    updatedAt: '2025-03-30T04:48:57.247Z',
    age: '25',
    barangay: 'Minaog',
    birthPlaceCity: 'Dipolog City',
    birthPlaceProvince: 'Zamboanga del Norte',
    birthPlaceRegion: 'Region 9',
    birthday: '2000-03-23T16:00:00.000Z',
    cityMunicipality: 'Dipolog City',
    civilStatus: 'single',
    contact: '09123456789',
    district: '1',
    educationAttainment: 'college level',
    employmentStatus: 'unemployed',
    firstname: 'prenz gatan',
    lastname: 'etbew',
    learnerOrTraineeOrStudentClassification: 'Solo Parent',
    middlename: 'gurdiel',
    nationality: 'Filipino',
    numberStreet: '3',
    province: 'Zamboanga del Norte',
    region: 'Region 9',
    sex: 'male',
    FathersContact: '09123456789',
    FathersEmail: 'gatan@gmail.com',
    FathersFirstName: 'Gatan',
    FathersLastName: 'Gatan',
    FathersMiddleName: 'Gatan',
    MothersContact: '09123456789',
    MothersEmail: 'gatan@gmail.com',
    MothersFirstName: 'Gatan',
    MothersLastName: 'Gatan',
    MothersMiddleName: 'Gatan',
    cocUrl: null,
    courseId: '67b8038015bb91b25b73684e',
    enrollStatus: 'Pending',
    goodMoralUrl: 'BSCS Logo.png',
    photoUrl: 'BSCS Logo.png',
    primarySchoolName: 'Dipolog City Central School',
    primarySchoolYear: '2007',
    psaUrl: 'BSCS Logo.png',
    reportCardUrl: 'BSCS Logo.png',
    secondarySchoolName: 'ZNNHS Turno',
    secondarySchoolYear: '2011',
    seniorHighSchoolName: 'n/a',
    seniorHighSchoolStrand: 'ICT',
    seniorHighSchoolYear: '2014',
    studentSemester: '2nd semester',
    studentYear: '2nd year',
    scholarshipId: '67e167358dbc00e962538da6',
    studentType: 'regular',
  },
  {
    _id: '67e7dbd095b2b0ca6dc96ea7',
    userId: '67e7dbd095b2b0ca6dc96ea5',
    firstname: 'carl vincent',
    middlename: '',
    lastname: 'mendoza',
    extensionName: '',
    numberStreet: 'Looc',
    barangay: 'Estaka',
    district: '1',
    cityMunicipality: 'Dipolog City',
    province: 'Zamboanga Del Norte',
    region: 'Region IX',
    emailFbAcc: '',
    contact: '09123456789',
    nationality: 'Filipino',
    sex: 'male',
    civilStatus: 'single',
    employmentStatus: 'unemployed',
    birthday: '2000-03-28T16:00:00.000Z',
    age: '25',
    birthPlaceCity: 'Dipolog City',
    birthPlaceProvince: 'Zamboanga Del Norte',
    birthPlaceRegion: 'Region IX',
    educationAttainment: 'others',
    learnerOrTraineeOrStudentClassification: 'Others',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-29T11:38:56.790Z',
    updatedAt: '2025-03-29T11:38:56.790Z',
    enrollStatus: 'Pending',
  },
  {
    _id: '67e7e21127c5ffac7309027d',
    userId: '67e7e21127c5ffac7309027b',
    firstname: 'john',
    middlename: '',
    lastname: 'doe',
    extensionName: '',
    numberStreet: 'Looc',
    barangay: 'Estaka',
    district: '1',
    cityMunicipality: 'Dipolog City',
    province: 'Zamboanga Del Norte',
    region: 'XI',
    emailFbAcc: '',
    contact: '09123456789',
    nationality: 'Filipino',
    sex: 'male',
    civilStatus: 'single',
    employmentStatus: 'unemployed',
    birthday: '2000-03-28T16:00:00.000Z',
    age: '25',
    birthPlaceCity: 'Dipolog City',
    birthPlaceProvince: 'Zamboanga Del Norte',
    birthPlaceRegion: 'Region XI',
    educationAttainment: 'others',
    learnerOrTraineeOrStudentClassification: 'Others',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-29T12:05:37.759Z',
    updatedAt: '2025-03-29T12:05:37.759Z',
    enrollStatus: 'Pending',
  },
  {
    _id: '67e8d0aa861a9e6f16b92b73',
    userId: '67e8d0aa861a9e6f16b92b71',
    firstname: 'mariel',
    middlename: 'logo',
    lastname: 'yangyang',
    extensionName: '',
    numberStreet: '1',
    barangay: 'Minaog',
    district: '1',
    cityMunicipality: 'Dipolog City',
    province: 'Zamboanga del Norte',
    region: 'Region 9',
    emailFbAcc: '',
    contact: '09123456789',
    nationality: 'Filipino',
    sex: 'female',
    civilStatus: 'single',
    employmentStatus: 'unemployed',
    birthday: '2000-03-29T16:00:00.000Z',
    age: '25',
    birthPlaceCity: 'Dipolog City',
    birthPlaceProvince: 'Zamboanga del Norte',
    birthPlaceRegion: 'Region 9',
    educationAttainment: 'college level',
    learnerOrTraineeOrStudentClassification: 'Others',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-30T05:03:38.735Z',
    updatedAt: '2025-03-30T05:03:38.735Z',
  },
  {
    _id: '67e8eb5f35739a84553dabe3',
    userId: '67e8eb5f35739a84553dabe1',
    firstname: 'cristine',
    middlename: '',
    lastname: 'labadlabad',
    extensionName: '',
    numberStreet: 'Looc',
    barangay: 'Estaka',
    district: '1',
    cityMunicipality: 'Dipolog City',
    province: 'Zamboanga Del Norte',
    region: 'qweqwe',
    emailFbAcc: '',
    contact: '09123456789',
    nationality: 'Filipino',
    sex: 'female',
    civilStatus: 'single',
    employmentStatus: 'unemployed',
    birthday: '2000-03-29T16:00:00.000Z',
    age: '25',
    birthPlaceCity: 'Dipolog City',
    birthPlaceProvince: 'Zamboanga Del Norte',
    birthPlaceRegion: 'Region IX',
    educationAttainment: 'others',
    learnerOrTraineeOrStudentClassification: 'Others',
    studentStatus: 'New Student',
    isVerified: true,
    createdAt: '2025-03-30T06:57:35.859Z',
    updatedAt: '2025-03-30T07:07:08.025Z',
    FathersContact: '',
    FathersEmail: '',
    FathersFirstName: 'n/a',
    FathersLastName: 'n/a',
    FathersMiddleName: '',
    MothersContact: '',
    MothersEmail: '',
    MothersFirstName: 'n/a',
    MothersLastName: 'n/a',
    MothersMiddleName: '',
    cocUrl: null,
    courseId: '67b8038015bb91b25b73684e',
    enrollStatus: 'Pending',
    goodMoralUrl: null,
    photoUrl: 'blob',
    primarySchoolName: 'qweqwe',
    primarySchoolYear: 'qweqwe',
    psaUrl: 'blob',
    reportCardUrl: 'blob',
    secondarySchoolName: 'qweqwe',
    secondarySchoolYear: 'qweqwe',
    seniorHighSchoolName: 'n/a',
    seniorHighSchoolStrand: '',
    seniorHighSchoolYear: '',
    studentSemester: '2nd semester',
    studentYear: '1st year',
    studentType: 'regular',
  },
];
