import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import Providers from '@/lib/query-provider';
import { auth } from '@/auth';
import MessageListener from '@/lib/MessageListener';
import { LoadingProvider } from '@/components/shared/nav/logout/LoadingContext';
import Warning from '@/components/shared/Warning';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Dipolog City Institute of Technology, INC.',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon-32x32.png',
  },
};
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  
  const session = await auth();
  console.log('session', session);
  return (
    <html lang='en' className='' suppressHydrationWarning>
      {/* <body className={`custom-scrollbar-body ${inter.className}`} > */}
      <body className={inter.className}>
        <Warning />
        <LoadingProvider>
          <Providers session={session}>
            {/* <MessageListener> */}
            {children}
            <Toaster position='top-center' reverseOrder={false} />
            {/* </MessageListener> */}
          </Providers>
        </LoadingProvider>
      </body>
    </html>
  );
}
