export const enrollmentRecordData = [
  {
    _id: '67dabece39851a77971eb903',
    category: 'College',
    profileId: '67ce93f59b82a9319407ab02',
    course: 'Bachelor of Science in Computer Science',
    courseCode: 'BSCS',
    blockType: {
      year: '4th year',
      semester: '1st semester',
      section: 'a',
    },
    studentType: 'regular',
    studentYear: '4th year',
    studentSemester: '1st semester',
    step: 6,
    schoolYear: 'SY2024-2025',
    enrollStatus: 'Enrolled',
    studentStatus: 'Transferee',
    studentSubjects: [
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '4th year',
          category: 'College',
          subjectCode: 'THS 101',
          name: 'Thesis 1',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'catherine',
          lastname: 'mamucay',
          extensionName: '',
          sex: 'female',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['F', 'Su'],
        startTime: '07:00',
        endTime: '08:30',
        room: {
          roomName: 'Lab 1',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd81',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '',
          category: 'College',
          subjectCode: 'ForLang 1',
          name: 'Foreign Language 1 (Mandarin)',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'abz',
          lastname: 'andilab',
          extensionName: '',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['Su'],
        startTime: '13:30',
        endTime: '15:00',
        room: {
          roomName: 'room 3',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd84',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '',
          category: 'College',
          subjectCode: 'Free-Elect 1',
          name: 'Free Elective 1',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'clarwill',
          lastname: 'amaro',
          middlename: 'm',
          extensionName: 'sr',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['M'],
        startTime: '08:30',
        endTime: '10:00',
        room: {
          roomName: 'room 117',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd88',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: 'CC 101',
          category: 'College',
          subjectCode: 'SP 1',
          name: 'Social Issues and Professional Practice',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'deana',
          middlename: 'deana',
          lastname: 'deana',
          extensionName: '',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['Sa', 'Su'],
        startTime: '15:00',
        endTime: '16:30',
        room: {
          roomName: 'room 121',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd8d',
      },
    ],
    payment: true,
    createdAt: '2025-03-19T12:55:42.271Z',
    updatedAt: '2025-03-19T12:54:32.537Z',
  },
  {
    _id: '67dabece39851a77971eb902',
    category: 'College',
    profileId: '67c5b0bd1e540d0e3085819d',
    course: 'Bachelor of Science in Computer Science',
    courseCode: 'BSCS',
    blockType: {
      year: '4th year',
      semester: '1st semester',
      section: 'a',
    },
    studentType: 'regular',
    studentYear: '4th year',
    studentSemester: '1st semester',
    step: 6,
    schoolYear: 'SY2024-2025',
    enrollStatus: 'Enrolled',
    studentStatus: 'Transferee',
    studentSubjects: [
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '4th year',
          category: 'College',
          subjectCode: 'THS 101',
          name: 'Thesis 1',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'catherine',
          lastname: 'mamucay',
          extensionName: '',
          sex: 'female',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['F', 'Su'],
        startTime: '08:30',
        endTime: '09:00',
        room: {
          roomName: 'Lab 1',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd81',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '',
          category: 'College',
          subjectCode: 'ForLang 1',
          name: 'Foreign Language 1 (Mandarin)',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'abz',
          lastname: 'andilab',
          extensionName: '',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['Su'],
        startTime: '16:00',
        endTime: '17:00',
        room: {
          roomName: 'room 3',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd84',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '',
          category: 'College',
          subjectCode: 'Free-Elect 1',
          name: 'Free Elective 1',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'clarwill',
          lastname: 'amaro',
          middlename: 'm',
          extensionName: 'sr',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['M'],
        startTime: '14:00',
        endTime: '15:00',
        room: {
          roomName: 'room 117',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd88',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: 'CC 101',
          category: 'College',
          subjectCode: 'SP 1',
          name: 'Social Issues and Professional Practice',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'deana',
          middlename: 'deana',
          lastname: 'deana',
          extensionName: '',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['Sa', 'Su'],
        startTime: '13:00',
        endTime: '14:00',
        room: {
          roomName: 'room 121',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd8d',
      },
    ],
    payment: true,
    createdAt: '2025-03-19T12:55:42.271Z',
    updatedAt: '2025-03-19T12:54:32.537Z',
  },
  {
    _id: '67c5b09a1e540d0e30858196',
    category: 'College',
    profileId: '67c5b09a1e540d0e30858196',
    course: 'Bachelor of Science in Computer Science',
    courseCode: 'BSCS',
    blockType: {
      year: '4th year',
      semester: '1st semester',
      section: 'a',
    },
    studentType: 'regular',
    studentYear: '4th year',
    studentSemester: '1st semester',
    step: 6,
    schoolYear: 'SY2024-2025',
    enrollStatus: 'Enrolled',
    studentStatus: 'Old Student',
    studentSubjects: [
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '4th year',
          category: 'College',
          subjectCode: 'THS 101',
          name: 'Thesis 1',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'catherine',
          lastname: 'mamucay',
          extensionName: '',
          sex: 'female',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['F', 'Su'],
        startTime: '08:30',
        endTime: '09:00',
        room: {
          roomName: 'Lab 1',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd81',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '',
          category: 'College',
          subjectCode: 'Rizal',
          name: "Rizal's Life & Works",
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'abz',
          lastname: 'andilab',
          extensionName: '',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['Su'],
        startTime: '16:00',
        endTime: '17:00',
        room: {
          roomName: 'room 3',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd84',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '',
          category: 'College',
          subjectCode: 'Free-Elect 1',
          name: 'Free Elective 1',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'clarwill',
          lastname: 'amaro',
          middlename: 'm',
          extensionName: 'sr',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['M'],
        startTime: '14:00',
        endTime: '15:00',
        room: {
          roomName: 'room 117',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd88',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: 'CC 101',
          category: 'College',
          subjectCode: 'SP 1',
          name: 'Social Issues and Professional Practice',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'nancy',
          middlename: '',
          lastname: 'daguplo',
          extensionName: '',
          sex: 'female',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['Sa', 'Su'],
        startTime: '13:00',
        endTime: '14:00',
        room: {
          roomName: 'room 121',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd8d',
      },
    ],
    payment: true,
    createdAt: '2025-03-19T12:55:42.271Z',
    updatedAt: '2025-03-19T12:54:32.537Z',
  },
  {
    _id: '67dabece39851a77971eb923',
    category: 'College',
    profileId: '67e7dbd095b2b0ca6dc96ea7',
    course: 'Bachelor of Science in Computer Science',
    courseCode: 'BSCS',
    blockType: {
      year: '4th year',
      semester: '1st semester',
      section: 'a',
    },
    studentType: 'regular',
    studentYear: '4th year',
    studentSemester: '1st semester',
    step: 5,
    schoolYear: 'SY2024-2025',
    enrollStatus: 'Enrolled',
    studentStatus: 'Transferee',
    studentSubjects: [
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '4th year',
          category: 'College',
          subjectCode: 'THS 101',
          name: 'Thesis 1',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'catherine',
          lastname: 'mamucay',
          extensionName: '',
          sex: 'female',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['F', 'Su'],
        startTime: '07:00',
        endTime: '08:30',
        room: {
          roomName: 'Lab 1',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd81',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '',
          category: 'College',
          subjectCode: 'ForLang 1',
          name: 'Foreign Language 1 (Mandarin)',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'abz',
          lastname: 'andilab',
          extensionName: '',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['Su'],
        startTime: '13:30',
        endTime: '15:00',
        room: {
          roomName: 'room 3',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd84',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: '',
          category: 'College',
          subjectCode: 'Free-Elect 1',
          name: 'Free Elective 1',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'clarwill',
          lastname: 'amaro',
          middlename: 'm',
          extensionName: 'sr',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['M'],
        startTime: '08:30',
        endTime: '10:00',
        room: {
          roomName: 'room 117',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd88',
      },
      {
        subject: {
          fixedRateAmount: '0.00',
          preReq: 'CC 101',
          category: 'College',
          subjectCode: 'SP 1',
          name: 'Social Issues and Professional Practice',
          lec: '3',
          lab: '0',
          unit: '3',
        },
        teacher: {
          firstname: 'nancy',
          middlename: '',
          lastname: 'daguplo',
          extensionName: '',
          sex: 'male',
        },
        blockType: {
          year: '4th year',
          semester: '1st semester',
          section: 'a',
        },
        days: ['Sa', 'Su'],
        startTime: '15:00',
        endTime: '16:30',
        room: {
          roomName: 'room 121',
        },
        status: 'Approved',
        profileId: '6740377fb3a524cc1f498a8d',
        firstGrade: '',
        secondGrade: '',
        thirdGrade: '',
        fourthGrade: '',
        averageTotal: '',
        _id: '67d2a4381718cb63e32bfd8d',
      },
    ],
    payment: false,
    createdAt: '2025-03-19T12:55:42.271Z',
    updatedAt: '2025-03-19T12:54:32.537Z',
  },
];
